name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup SSH for localhost
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl start ssh
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        ssh-keyscan -H localhost >> ~/.ssh/known_hosts
    - name: Format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy
    - name: Test
      run: cargo test --verbose
