name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain-file: rust-toolchain.toml
    - name: Format
      run: cargo fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain-file: rust-toolchain.toml
    - name: Lint
      run: cargo clippy

  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain-file: rust-toolchain.toml
    - name: Documentation
      run: cargo doc --no-deps
      env:
        RUSTDOCFLAGS: -D warnings

  test:
    runs-on: ubuntu-latest
    needs: [format, lint, documentation]
    steps:
    - uses: actions/checkout@v5
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain-file: rust-toolchain.toml
    - name: Setup SSH for localhost
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl start ssh
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ""
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        ssh-keyscan -H localhost >> ~/.ssh/known_hosts
    - name: Install cargo-nextest
      run: cargo install cargo-nextest
    - name: Test
      run: |
        # Run tests with nextest for better output
        cargo nextest run --no-capture 2>&1 | tee test_output.log
    - name: Doctests
      run: cargo test --doc
    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: test_output.log
